apiVersion: batch/v1
kind: Job
metadata:
  name: zeebe-restore-$NODEID
spec:
  template:
    spec:
      serviceAccountName: "ccs23-restore-client"
      containers:
        - name: zeebe
          image: camunda/zeebe:8.2.3
          command: ["/usr/local/zeebe/bin/restore", "--backupId=$BACKUPID"]
          volumeMounts:
            - name: data
              mountPath: "/usr/local/zeebe/data"
          env:
            - name: "ZEEBE_BROKER_CLUSTER_CLUSTERNAME"
              value: "ccs23-dev-zeebe"
            - name: "ZEEBE_BROKER_CLUSTER_NODEID"
              value: "$NODEID"
            - name: "ZEEBE_BROKER_CLUSTER_CLUSTERSIZE"
              value: "3"
            - name: "ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT"
              value: "3"
            - name: "ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR"
              value: "3"
            - name: "ZEEBE_BROKER_DATA_BACKUP_STORE"
              value: "gcs"
            - name: "ZEEBE_BROKER_DATA_BACKUP_GCS_BUCKETNAME"
              value: "ccs23-backup"
            - name: "ZEEBE_BROKER_DATA_BACKUP_GCS_BASEPATH"
              value: "zeebe"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-ccs23-dev-zeebe-$NODEID
      restartPolicy: OnFailure
